from ai_tools.db import get_connection

_ALARM_CODES = {
    1: "Wrong model configuration",
    2: "Wrong Outdoor Unit model configuration",
    3: "Wrong Indoor Unit model configuration",
    4: "Emergency mode manual activation",
    10: "Heat pump not available",
    11: "Boiler not available",
    12: "Electric heater not available",
    13: "DHW electric heater not available",
    14: "Buffer electric heater not available",
    15: "External Chiller not available",
    16: "External Chiller not available",
    20: "DHW service not available",
    21: "DHW recirculation not available",
    22: "Pool service not available",
    23: "Heating service not available",
    24: "Active Cooling service not available",
    25: "Passive Cooling service not available",
    30: "SG1 group not available",
    31: "SG2 group not available",
    32: "SG3 group not available",
    33: "SG4 group not available",
    34: "SG5 group not available",
    35: "Lock alarm reset",
    40: "High discharge pressure",
    41: "Low suction pressure",
    42: "High discharge temperature",
    43: "High evaporation temperature",
    44: "Low condensation temperature",
    45: "Low superheating",
    46: "High superheating",
    50: "Inverter alarm",
    51: "Safety stop pressure/flow switch",
    52: "Inverter locked (switch off 2 minutes)",
    53: "Low Voltage",
    54: "Wrong configuration PowerPlus",
    60: "Low brine pressure",
    61: "Low brine temperature",
    62: "High brine temperature",
    63: "Low clima pressure",
    64: "Low outdoor temperature",
    65: "High outdoor temperature",
    66: "Low evaporator flow",
    67: "Sources out of range",
    70: "pCO fault: clock / EEPROM",
    71: "pCO fault: driver EEV",
    72: "e-Source Alarm",
    73: "e-Source OFF",
    80: "Discharge pressure sensor broken or disconnected",
    81: "Discharge temperature sensor broken or disconnected",
    82: "Suction pressure sensor broken or disconnected",
    83: "Suction temperature sensor broken or disconnected",
    84: "Intermediate pressure sensor broken or disconnected",
    85: "Brine circuit pressure sensor broken or disconnected",
    86: "Brine circuit supply temperature sensor broken or disconnected",
    87: "Brine circuit return temperature sensor broken or disconnected",
    88: "Production circuit pressure sensor broken or disconnected",
    89: "Production circuit supply temperature sensor broken or disconnected",
    90: "Production circuit return temperature sensor broken or disconnected",
    91: "Group 1 temperature sensor broken or disconnected",
    92: "Group 2 temperature sensor broken or disconnected",
    93: "Group 3 temperature sensor broken or disconnected",
    94: "Group 4 temperature sensor broken or disconnected",
    95: "Group 5 temperature sensor broken or disconnected",
    96: "DHW temperature sensor broken or disconnected",
    97: "DHW recirculation temperature sensor broken or disconnected",
    98: "Pool temperature sensor broken or disconnected",
    99: "Heating buffer tank temperature sensor broken or disconnected",
    100: "Cooling buffer tank temperature sensor broken or disconnected",
    101: "Outdoor temperature sensor broken or disconnected",
    102: "Boiler temperature sensor broken or disconnected",
    103: "Air unit return temperature sensor broken or disconnected",
    104: "Production circuit 2 supply temperature sensor broken or disconnected",
    105: "Production circuit 2 return temperature sensor broken or disconnected",
    106: "Condenser outlet temperature sensor broken or disconnected",
    107: "Solar tank temperature sensor broken or disconnected",
    108: "Heating/cooling buffer tank temperature sensor broken or disconnected",
    109: "Chiller temperature sensor broken or disconnected",
    110: "Condenser 2 outlet temperature sensor broken or disconnected",
    111: "Oil circuit pressure sensor broken or disconnected",
    112: "Oil circuit supply temperature sensor broken or disconnected",
    113: "Oil circuit return temperature sensor broken or disconnected",
    114: "Inverter cooling outlet temperature sensor broken or disconnected",
    115: "Inverter cooling inlet temperature sensor broken or disconnected",
    120: "Thermostat th-Tune 1 fault",
    121: "Thermostat th-Tune 2 fault",
    122: "Thermostat th-Tune 3 fault",
    123: "Thermostat th-Tune 4 fault",
    124: "Thermostat th-Tune 5 fault",
    130: "Thermostat th-T 1 fault",
    131: "Thermostat th-T 2 fault",
    132: "Thermostat th-T 3 fault",
    133: "Thermostat th-T 4 fault",
    134: "Thermostat th-T 5 fault",
    140: "Device failure",
    141: "Device failure",
    142: "Device failure",
    143: "Device failure",
    144: "Device failure",
    150: "Slaves not available",
    151: "Heat Pump 1 not available",
    152: "Heat Pump 2 not available",
    153: "Heat Pump 3 not available",
    154: "Heat Pump 4 not available",
    155: "Heat Pump 5 not available",
    156: "Heat Pump 6 not available",
    160: "pCOe 1 offline",
    161: "pCOe 2 offline",
    162: "Inverter offline",
    163: "Cascade offline",
    164: "e-Manager offline",
    165: "e-Source offline",
    166: "Outdoor unit offline",
    167: "EVD offline",
    168: "Grid Meter offline",
    169: "cpCOe1 offline",
    170: "cpCOe2 offline",
    171: "Heat Pump offline",
    172: "Heat Pump 1 offline",
    173: "Heat Pump 2 offline",
    174: "Heat Pump 3 offline",
    175: "Heat Pump 4 offline",
    176: "Heat Pump 5 offline",
    177: "Heat Pump 6 offline",
    178: "Outdoor BUS Temp probe offline",
    180: "Thermostat th-Tune 1 offline",
    181: "Thermostat th-Tune 2 offline",
    182: "Thermostat th-Tune 3 offline",
    183: "Thermostat th-Tune 4 offline",
    184: "Thermostat th-Tune 5 offline",
    190: "Thermostat th-T 1 offline",
    191: "Thermostat th-T 2 offline",
    192: "Thermostat th-T 3 offline",
    193: "Thermostat th-T 4 offline",
    194: "Thermostat th-T 5 offline",
    200: "Device offline",
    201: "Device offline",
    202: "Device offline",
    203: "Device offline",
    204: "Device offline",
    220: "Legionella failed",
    221: "Defrosting failed",
    230: "Service fault DHW",
    231: "Service fault Pool",
    232: "Service fault Heating",
    233: "Service fault Active cooling",
    234: "Service fault Passive cooling",
    240: "Simultaneous heat/cool SG1",
    241: "Simultaneous heat/cool SG2",
    242: "Simultaneous heat/cool SG3",
    243: "Simultaneous heat/cool SG4",
    244: "Simultaneous heat/cool SG5",
    250: "Low brine pressure warning",
    251: "Low production circuit pressure warning",
    252: "High brine pressure warning",
    253: "High production circuit pressure warning",
}

_ALARM_COLS = [
    "lock_alarm_code",
    "long_time_alarm_code",
    "recurrence_alarm_code",
    "active_alarm_code_1",
    "active_alarm_code_2",
    "active_alarm_code_3",
    "active_alarm_code_4",
    "active_alarm_code_5",
]


def get_recent_alarms(heatpump_id):
    conn = get_connection()
    cur = conn.cursor()

    cur.execute(
        """
        SELECT *
        FROM alarms
        WHERE heatpump_id = ?
        ORDER BY timestamp DESC
        LIMIT 5
    """,
        (heatpump_id,),
    )

    rows = cur.fetchall()

    if not rows:
        return []

    columns = [desc[0] for desc in cur.description]
    result = []
    for row in rows:
        record = dict(zip(columns, row))
        for col in _ALARM_COLS:
            if col in record and record[col]:
                record[col] = _ALARM_CODES.get(record[col], f"Alarm {record[col]}")
        result.append(record)

    cur.close()
    conn.close()

    return result
